// Registry of visualizations. Adding a new one only requires appending an entry here
// and creating its component; the router and home page pick it up automatically.

import type { ComponentType } from "react";
import { GaloisGroupVisualization } from "./galois-group";
import { LatticeVisualization } from "./lattice";
import { SvpCvpVisualization } from "./svp-cvp";
import { BallPackingVisualization } from "./ball-packing";
import { GridForcingVisualization } from "./grid-forcing";

export type Visualization = {
  id: string;            // URL slug, e.g. "galois-group"
  title: string;
  description: string;
  status: "ready" | "planned";
  Component?: ComponentType;
};

export const visualizations: Visualization[] = [
  {
    id: "galois-group",
    title: "Galois group of a polynomial",
    description:
      "Enter a polynomial over ℚ and see the group of allowable permutations of its roots, together with the subgroup lattice and intermediate fields.",
    status: "ready",
    Component: GaloisGroupVisualization,
  },
  {
    id: "lattice",
    title: "Lattice generated by vectors",
    description:
      "Enter vectors in up to 3 dimensions and see the lattice of their integer combinations in 3-D, with checks on rank, linear independence, basis-ness, and covolume.",
    status: "ready",
    Component: LatticeVisualization,
  },
  {
    id: "svp-cvp",
    title: "Shortest & closest vectors (SVP / CVP)",
    description:
      "Step through Gauss–Lagrange reduction to find the shortest vector of a 2-D lattice, and use Babai rounding to find the closest lattice point to a target in 2-D or 3-D.",
    status: "ready",
    Component: SvpCvpVisualization,
  },
  {
    id: "ball-packing",
    title: "Balls in a square, and on a torus",
    description:
      "Drop n balls of radius r on a square or on the flat torus, see exactly which area each ball owns and which area they are forced to share, and watch the pigeonhole principle decide when overlap is unavoidable.",
    status: "ready",
    Component: BallPackingVisualization,
  },
  {
    id: "grid-forcing",
    title: "Forcing a shape on a grid",
    description:
      "Place dots on an N × N grid and see at once whether some of them form an isosceles triangle, a square, or a shape you drew yourself; then have a SAT solver compute the smallest number of dots that makes it unavoidable, and read the reduction that turns the question into 3-SAT.",
    status: "ready",
    Component: GridForcingVisualization,
  },
  {
    id: "ideal-lattice",
    title: "Ideal lattice in ℤ/n",
    description:
      "Visualize the lattice of ideals (= divisors) in ℤ/n and how quotients pick out the prime structure.",
    status: "planned",
  },
  {
    id: "free-group",
    title: "Cayley graph of free / finitely-presented groups",
    description:
      "Generate the Cayley graph of small groups given by presentation and explore how relations collapse it.",
    status: "planned",
  },
];

export function findVisualization(id: string): Visualization | undefined {
  return visualizations.find((v) => v.id === id);
}
