// Compute the Galois group of a polynomial over ℚ.
// Supports degrees 1, 2, 3, 4 exactly. Degree 5+ returns "Unknown" with a note.

import type { Rational } from "./rational";
import {
  ONE,
  ZERO,
  add,
  sub,
  mul,
  neg,
  rat,
  isZero,
  format as fmtRat,
  rationalSqrt,
} from "./rational";
import type { Polynomial } from "./polynomial";
import {
  deg,
  makeMonic,
  squareFreePart,
  rationalRoots,
  factorOutRationalRoots,
  discriminant,
  isPerfectSquare,
  formatPoly,
} from "./polynomial";
import { qIsSquare, qMul, qSub, qSquare } from "./quadField";
import type { GroupName, NamedGroup } from "./groups";
import { makeNamedGroup } from "./groups";

export type GaloisResult =
  | {
      kind: "ok";
      original: Polynomial;
      monic: Polynomial;
      squareFree: Polynomial;
      factorization: Factor[];
      irreducible: boolean;
      degreeAfterDedup: number;
      group: NamedGroup;
      discriminant: Rational;
      discriminantIsSquare: boolean;
      resolventCubic: Polynomial | null;       // only for degree 4
      resolventRationalRoot: Rational | null;  // only for degree 4 (when applicable)
      note: string;
    }
  | { kind: "unsupported"; reason: string; original: Polynomial }
  | { kind: "error"; reason: string; original: Polynomial };

export type Factor = {
  rationalRoots: Rational[];     // simple rational roots peeled off
  remainder: Polynomial | null;  // the remaining (presumed irreducible) factor, monic
};

// ---- Top-level driver ----

export function computeGalois(input: Polynomial): GaloisResult {
  const original = input;
  if (input.length === 0) {
    return { kind: "error", reason: "Polynomial is identically zero.", original };
  }
  if (deg(input) === 0) {
    return { kind: "error", reason: "Polynomial is a nonzero constant — no roots.", original };
  }
  const monic = makeMonic(input);
  const sqfree = squareFreePart(monic);
  const { roots: rRoots, remainder } = factorOutRationalRoots(sqfree);
  const factor: Factor = { rationalRoots: rRoots, remainder: deg(remainder) >= 1 ? remainder : null };
  const factorization: Factor[] = [factor];
  const remDeg = factor.remainder ? deg(factor.remainder) : 0;
  const totalSplittingDegree = rRoots.length + remDeg;

  // The "active" polynomial for Galois group computation is the remainder (if irreducible).
  // If remainder splits as a product of further-irreducible factors of degree ≥ 2, the splitting
  // field is the compositum. We currently only support the case where the remainder is itself
  // irreducible — i.e., we don't further factor degree ≥ 2 polynomials over ℚ.
  let group: NamedGroup;
  let disc: Rational = ZERO;
  let discSq = false;
  let resolvent: Polynomial | null = null;
  let resolventTheta: Rational | null = null;
  let note = "";

  // Splitting field Galois group acts on all distinct roots; rational roots contribute the
  // trivial action. So we name the group by its action on the non-rational roots.
  if (!factor.remainder) {
    group = makeNamedGroup("Trivial", Math.max(totalSplittingDegree, 1));
    note = "All roots are rational; the splitting field is ℚ itself.";
    return {
      kind: "ok",
      original,
      monic,
      squareFree: sqfree,
      factorization,
      irreducible: false,
      degreeAfterDedup: totalSplittingDegree,
      group,
      discriminant: ZERO,
      discriminantIsSquare: true,
      resolventCubic: null,
      resolventRationalRoot: null,
      note,
    };
  }

  const f = factor.remainder; // monic, no rational roots, square-free
  const n = deg(f);
  disc = discriminant(f);
  discSq = isPerfectSquare(disc);

  if (n === 1) {
    // Shouldn't happen — degree 1 has a rational root.
    group = makeNamedGroup("Trivial", n);
    note = "Linear factor — already in ℚ.";
  } else if (n === 2) {
    group = makeNamedGroup("C_2", 2);
    note = "Irreducible quadratic — Galois group is ℤ/2 generated by the root-swap.";
  } else if (n === 3) {
    if (discSq) {
      group = makeNamedGroup("C_3", 3);
      note = "Discriminant is a perfect square in ℚ — Galois group is A₃ = ℤ/3 (only cyclic permutations of roots).";
    } else {
      group = makeNamedGroup("S_3", 3);
      note = "Discriminant is not a square in ℚ — full symmetric group S₃ acts on the 3 roots.";
    }
  } else if (n === 4) {
    // First check whether the quartic actually factors over ℚ as a product of two quadratics.
    // (We've already peeled off rational roots, so this is the remaining possible reducibility.)
    const reduce = tryFactorQuarticIntoQuadratics(f);
    if (reduce) {
      const [g1, g2] = reduce.factors;
      // Compute Galois group of the compositum of the splitting fields of g1, g2.
      // Each g_i is monic quadratic over ℚ. Its splitting field is ℚ(√disc(g_i)).
      const d1 = discriminant(g1);
      const d2 = discriminant(g2);
      const d1IsSq = isPerfectSquare(d1);
      const d2IsSq = isPerfectSquare(d2);
      if (d1IsSq && d2IsSq) {
        group = makeNamedGroup("Trivial", 4);
        note = `The quartic factors over ℚ as (${formatPoly(g1)})·(${formatPoly(g2)}), and each quadratic factor splits over ℚ — every root is rational.`;
      } else if (d1IsSq || d2IsSq) {
        group = makeNamedGroup("C_2", 2);
        note = `The quartic factors over ℚ as (${formatPoly(g1)})·(${formatPoly(g2)}); one factor splits but the other is irreducible — Galois group is ℤ/2.`;
      } else {
        // Both irreducible. Compositum has Gal C_2 if ℚ(√d_1) = ℚ(√d_2), else V_4.
        const same = isPerfectSquare(mul(d1, d2));
        if (same) {
          group = makeNamedGroup("C_2", 2);
          note = `The quartic factors over ℚ as (${formatPoly(g1)})·(${formatPoly(g2)}); both quadratics share the same splitting field — Galois group is ℤ/2.`;
        } else {
          group = makeNamedGroup("V_4", 4);
          note = `The quartic factors over ℚ as (${formatPoly(g1)})·(${formatPoly(g2)}); the splitting field is the biquadratic compositum ℚ(√${fmtRat(d1)}, √${fmtRat(d2)}) — Galois group is V₄.`;
        }
      }
      resolvent = reduce.resolvent;
      resolventTheta = reduce.theta;
    } else {
      const result = quarticGalois(f, disc, discSq);
      group = makeNamedGroup(result.name, 4);
      resolvent = result.resolvent;
      resolventTheta = result.theta;
      note = result.note;
    }
  } else {
    return {
      kind: "unsupported",
      reason: `Galois group computation for irreducible polynomials of degree ${n} is not implemented in this tool. (In general it is much harder — degree 5 is the famous Abel–Ruffini boundary.)`,
      original,
    };
  }

  return {
    kind: "ok",
    original,
    monic,
    squareFree: sqfree,
    factorization,
    irreducible: rRoots.length === 0,
    degreeAfterDedup: totalSplittingDegree,
    group,
    discriminant: disc,
    discriminantIsSquare: discSq,
    resolventCubic: resolvent,
    resolventRationalRoot: resolventTheta,
    note,
  };
}

// Try to factor a monic quartic f over ℚ as a product of two monic quadratics.
// Returns the factors plus the resolvent and the witness rational root θ if successful.
function tryFactorQuarticIntoQuadratics(
  f: Polynomial,
): { factors: [Polynomial, Polynomial]; resolvent: Polynomial; theta: Rational } | null {
  const e = f[0];
  const dCoef = f[1];
  const c = f[2];
  const b = f[3];

  const coeff0 = neg(add(sub(mul(mul(b, b), e), mul(mul(rat(4), c), e)), mul(dCoef, dCoef)));
  const coeff1 = sub(mul(b, dCoef), mul(rat(4), e));
  const coeff2 = neg(c);
  const resolvent: Polynomial = [coeff0, coeff1, coeff2, ONE];
  const gRoots = rationalRoots(resolvent);

  for (const theta of gRoots) {
    const alpha = sub(mul(b, b), mul(rat(4), sub(c, theta))); // b² − 4(c − θ)
    const beta = sub(mul(theta, theta), mul(rat(4), e));      // θ² − 4e
    if (!isPerfectSquare(alpha) || !isPerfectSquare(beta)) continue;
    // (r_i + r_j) ∈ ℚ and r_i·r_j ∈ ℚ. Pick one sign convention for the factorization.
    const sqA = rationalSqrt(alpha)!;        // ≥ 0
    const sqB = rationalSqrt(beta)!;          // ≥ 0
    // s = r_i + r_j satisfies t² + b t + (c − θ) = 0  →  s = (−b ± √α)/2
    // p = r_i·r_j satisfies   t² − θ t + e   = 0      →  p = (θ ± √β)/2
    // We pick the (+, +) sign for the first quadratic and the conjugate for the second.
    // The product matches f regardless of which signs we pair (just swaps the factors).
    const half = rat(1, 2);
    const s1 = mul(half, add(neg(b), sqA));
    const p1 = mul(half, add(theta, sqB));
    const s2 = sub(neg(b), s1); // s1 + s2 = −b
    const p2 = sub(theta, p1);  // p1 + p2 = θ ... wait, p1 + p2 should equal θ from Vieta on t² − θ t + e
    // Quadratic factors: x² − s_i x + p_i? Or x² + s_i x + ... ? Compare coefficients.
    // (x² + α x + β)(x² + γ x + δ) expansion has β + δ + αγ as x² coeff.
    // Our s_i = r_i + r_j, so quadratic with roots r_i, r_j is x² − (r_i+r_j) x + r_i r_j.
    // → factor = x² − s_i x + p_i.
    const g1: Polynomial = [p1, neg(s1), ONE];
    const g2: Polynomial = [p2, neg(s2), ONE];
    // Sanity check that product matches f.
    // (We trust it does given the algebra, but guard against degenerate cases.)
    return { factors: [g1, g2], resolvent, theta };
  }
  return null;
}

// ---- Quartic Galois group via the resolvent cubic + ℚ(√d) square test ----

function quarticGalois(
  f: Polynomial,
  _disc: Rational,
  discSq: boolean,
): { name: GroupName; resolvent: Polynomial; theta: Rational | null; note: string } {
  // f is monic of degree 4 with no rational roots, square-free.
  // f(x) = x^4 + b x^3 + c x^2 + d x + e
  const e = f[0];
  const dCoef = f[1];
  const c = f[2];
  const b = f[3];

  // Resolvent cubic g(y) = y^3 − c y^2 + (b d − 4 e) y − (b² e − 4 c e + d²)
  const coeff0 = neg(
    add(sub(mul(mul(b, b), e), mul(mul(rat(4), c), e)), mul(dCoef, dCoef)),
  );
  const coeff1 = sub(mul(b, dCoef), mul(rat(4), e));
  const coeff2 = neg(c);
  const resolvent: Polynomial = [coeff0, coeff1, coeff2, ONE];

  const gRoots = rationalRoots(resolvent);

  if (gRoots.length === 0) {
    return {
      name: discSq ? "A_4" : "S_4",
      resolvent,
      theta: null,
      note: discSq
        ? "Resolvent cubic is irreducible and discriminant is a square — Galois group is A₄ (12 even permutations)."
        : "Resolvent cubic is irreducible and discriminant is not a square — Galois group is S₄, the full symmetric group on 4 roots.",
    };
  }

  if (gRoots.length >= 2) {
    // Three rational roots (by Vieta, if two are rational the third is too).
    return {
      name: "V_4",
      resolvent,
      theta: gRoots[0],
      note: "Resolvent cubic factors completely over ℚ — Galois group is V₄ = ℤ/2 × ℤ/2.",
    };
  }

  // Exactly one rational root θ: group is C₄ or D₄.
  const theta = gRoots[0];
  const alpha = sub(mul(b, b), mul(rat(4), sub(c, theta))); // b² − 4(c − θ)
  const beta = sub(mul(theta, theta), mul(rat(4), e));      // θ² − 4e

  const aSq = isPerfectSquare(alpha);
  const bSq = isPerfectSquare(beta);
  const abSq = isPerfectSquare(mul(alpha, beta));

  // Determine ℚ₂ = ℚ(s, p) and its degree over ℚ.
  // We need to know which square root, if any, generates ℚ₂ (= ℚ(√d) for some d ∈ ℚ).
  // Cases:
  //   (a) α is a square in ℚ and β is a square in ℚ      → ℚ₂ = ℚ        (degenerate; usually impossible for irreducible f)
  //   (b) α is a square in ℚ, β is not                    → ℚ₂ = ℚ(√β)
  //   (c) α is not a square in ℚ, β is a square in ℚ      → ℚ₂ = ℚ(√α)
  //   (d) neither square, but αβ is a square              → ℚ(√α) = ℚ(√β), so ℚ₂ = ℚ(√α)
  //   (e) neither, αβ also not a square                   → ℚ₂ = ℚ(√α, √β), biquadratic of degree 4

  if (!aSq && !bSq && !abSq) {
    // Case (e): ℚ₂ is biquadratic of degree 4. Then [K:Q] = 8 and Galois group is D₄.
    return {
      name: "D_4",
      resolvent,
      theta,
      note: "Resolvent cubic has exactly one rational root, and ℚ(√α) ≠ ℚ(√β) — Galois group is D₄ (order 8).",
    };
  }

  // Cases (a)–(d): ℚ₂ is at most quadratic over ℚ. Build it.
  let qExt: Rational | null; // K_2 = ℚ if null, else ℚ(√qExt)
  if (aSq && bSq) {
    qExt = null;
  } else if (aSq) {
    qExt = beta;
  } else if (bSq) {
    qExt = alpha;
  } else {
    // abSq: ℚ(√α) = ℚ(√β)
    qExt = alpha;
  }

  // Build s = (-b + √α)/2  and  p = (θ + √β)/2  as elements of ℚ₂.
  // s_q + s_k √qExt and similarly for p.
  // √α in ℚ₂: if α square in ℚ, equals sqrt(α). Else α = qExt · u² for some u ∈ ℚ, and √α = u·√qExt.
  // (Case "abSq" handled by using qExt = α, hence √α = √qExt has k=1; and β = α·(square), so √β = sqrt(β/α)·√α = sqrt(β·α)/α·α =... we compute directly.)

  const sqrtAlphaInK2 = sqrtRationalInK2(alpha, qExt);
  const sqrtBetaInK2 = sqrtRationalInK2(beta, qExt);
  if (!sqrtAlphaInK2 || !sqrtBetaInK2) {
    // Shouldn't happen given the case analysis above; fall back to D_4 to be safe.
    return {
      name: "D_4",
      resolvent,
      theta,
      note: "Quartic Galois group determination fell back to D₄ (internal: √α or √β not representable in ℚ₂).",
    };
  }

  // Currently both sqrtAlphaInK2 and sqrtBetaInK2 are pairs (a, b) representing a + b·√qExt
  // (with the convention qExt may be null when both are pure rationals).

  const twoInv = { n: 1n, d: 2n }; // 1/2 as a Rational
  const sQ = mul(twoInv, add(neg(b), sqrtAlphaInK2.q));
  const sK = mul(twoInv, sqrtAlphaInK2.k);
  const pQ = mul(twoInv, add(theta, sqrtBetaInK2.q));
  const pK = mul(twoInv, sqrtBetaInK2.k);

  // δ_1 = s² − 4p,   δ_2 = (b+s)² − 4(θ − p).
  // Compute in ℚ(√qExt). If qExt is null, treat as ℚ (k components must remain zero).
  const dForQ = qExt ?? rat(1); // unused if both k=0 throughout
  const sElt = { q: sQ, k: sK };
  const pElt = { q: pQ, k: pK };
  const thetaElt = { q: theta, k: ZERO };
  const fourPElt = { q: mul(rat(4), pElt.q), k: mul(rat(4), pElt.k) };
  const delta1 = qSub(qSquare(sElt, dForQ), fourPElt);
  const bPlusS = { q: add(b, sQ), k: sK };
  const thetaMinusP = qSub(thetaElt, pElt);
  const fourTmp = { q: mul(rat(4), thetaMinusP.q), k: mul(rat(4), thetaMinusP.k) };
  const delta2 = qSub(qSquare(bPlusS, dForQ), fourTmp);
  const prod = qMul(delta1, delta2, dForQ);

  // If qExt is null, all k components above are zero, so we're really in ℚ.
  // Then ℚ₂ = ℚ has degree 1, splitting field has degree ≤ 4, etc. — but irreducibility of f
  // forces a contradiction in this branch. Defensive: return V_4.
  if (qExt === null) {
    return {
      name: "V_4",
      resolvent,
      theta,
      note: "Resolvent has exactly one rational root and both α, β are squares in ℚ — V₄.",
    };
  }

  const c4 =
    qIsSquare(delta1, qExt) || qIsSquare(delta2, qExt) || qIsSquare(prod, qExt);

  return c4
    ? {
        name: "C_4",
        resolvent,
        theta,
        note: "Resolvent has exactly one rational root and a quadratic factor of f splits over ℚ(√α) (or ℚ(√β)) — Galois group is ℤ/4.",
      }
    : {
        name: "D_4",
        resolvent,
        theta,
        note: "Resolvent has exactly one rational root and f remains irreducible over ℚ(√α) and ℚ(√β) — Galois group is D₄ (order 8).",
      };
}

// √v as q + k·√qExt with q, k ∈ ℚ.
// If qExt is null, only the rational sqrt is possible (k = 0).
function sqrtRationalInK2(v: Rational, qExt: Rational | null): { q: Rational; k: Rational } | null {
  // Try pure rational sqrt first.
  if (v.n >= 0n) {
    const r = rationalSqrt(v);
    if (r !== null) return { q: r, k: ZERO };
  }
  if (qExt === null) return null;
  // v = qExt · u² ?
  // We need v/qExt to be a non-negative rational square.
  if (isZero(qExt)) return null;
  const ratio = { n: v.n * qExt.d, d: v.d * qExt.n }; // v / qExt (not yet reduced, but rationalSqrt handles)
  // Normalize sign of denominator
  let nr = ratio.n;
  let dr = ratio.d;
  if (dr < 0n) {
    nr = -nr;
    dr = -dr;
  }
  if (nr < 0n) return null;
  // Use rationalSqrt
  const reduced = rat(nr, dr);
  const u = rationalSqrt(reduced);
  if (u === null) return null;
  return { q: ZERO, k: u };
}

// ---- Pretty descriptions ----

export function describeFactorization(facts: Factor[]): string {
  const parts: string[] = [];
  for (const f of facts) {
    for (const r of f.rationalRoots) parts.push(`(x − ${fmtRat(r)})`);
    if (f.remainder) parts.push(`[${formatPoly(f.remainder)}]`);
  }
  return parts.join(" · ");
}
