// Named finite groups (Galois groups of degree ≤ 4 plus trivial) with explicit
// element lists (as permutations of {0,..,n-1}) and subgroup lattices.

export type Perm = number[]; // perm[i] = σ(i)

export function permId(n: number): Perm {
  return Array.from({ length: n }, (_, i) => i);
}

export function permCompose(a: Perm, b: Perm): Perm {
  // (a∘b)(i) = a(b(i))
  return b.map((bi) => a[bi]);
}

export function permEqual(a: Perm, b: Perm): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

export function permKey(a: Perm): string {
  return a.join(",");
}

export function permInverse(a: Perm): Perm {
  const inv = new Array(a.length).fill(0);
  for (let i = 0; i < a.length; i++) inv[a[i]] = i;
  return inv;
}

export function permOrder(a: Perm): number {
  let cur = a;
  let n = 1;
  const id = permId(a.length);
  while (!permEqual(cur, id)) {
    cur = permCompose(a, cur);
    n++;
    if (n > 1000) return -1;
  }
  return n;
}

// Convert a permutation to cycle notation, e.g. "(1 2 3)(4 5)" using 1-based indices.
export function permToCycles(a: Perm): string {
  const n = a.length;
  const seen = new Array<boolean>(n).fill(false);
  const cycles: string[] = [];
  for (let i = 0; i < n; i++) {
    if (seen[i]) continue;
    let j = i;
    const cyc: number[] = [];
    while (!seen[j]) {
      seen[j] = true;
      cyc.push(j + 1);
      j = a[j];
    }
    if (cyc.length > 1) cycles.push(`(${cyc.join(" ")})`);
  }
  return cycles.length === 0 ? "e" : cycles.join("");
}

export type GroupName =
  | "Trivial"
  | "C_2"
  | "C_3"
  | "C_4"
  | "V_4"
  | "S_3"
  | "D_4"
  | "A_4"
  | "S_4";

export type NamedGroup = {
  name: GroupName;
  prettyName: string;       // "ℤ/2", "S₄", "V₄ = ℤ/2 × ℤ/2", etc.
  order: number;
  degree: number;            // number of points it acts on
  elements: Perm[];
  isAbelian: boolean;
  description: string;       // one-line description for the UI
};

// ---- Element-list generators ----

function transpositions(n: number, pairs: [number, number][]): Perm {
  const p = permId(n);
  for (const [a, b] of pairs) {
    [p[a], p[b]] = [p[b], p[a]];
  }
  return p;
}

function cycle(n: number, items: number[]): Perm {
  // items = [a_0, a_1, ..., a_{k-1}] means a_0 → a_1, a_1 → a_2, ..., a_{k-1} → a_0
  const p = permId(n);
  for (let i = 0; i < items.length; i++) {
    p[items[i]] = items[(i + 1) % items.length];
  }
  return p;
}

// Close a set of generators under composition (BFS).
function closure(gens: Perm[], degree: number): Perm[] {
  const id = permId(degree);
  const seen = new Map<string, Perm>();
  seen.set(permKey(id), id);
  const queue: Perm[] = [id];
  while (queue.length) {
    const cur = queue.shift()!;
    for (const g of gens) {
      const next = permCompose(g, cur);
      const k = permKey(next);
      if (!seen.has(k)) {
        seen.set(k, next);
        queue.push(next);
      }
    }
  }
  return [...seen.values()];
}

function isAbelianGroup(elts: Perm[]): boolean {
  for (let i = 0; i < elts.length; i++) {
    for (let j = i + 1; j < elts.length; j++) {
      const ab = permCompose(elts[i], elts[j]);
      const ba = permCompose(elts[j], elts[i]);
      if (!permEqual(ab, ba)) return false;
    }
  }
  return true;
}

// ---- Named groups for degrees 1-4 ----

export function makeNamedGroup(name: GroupName, degree: number): NamedGroup {
  let elements: Perm[];
  let prettyName = "";
  let description = "";
  switch (name) {
    case "Trivial": {
      elements = [permId(degree)];
      prettyName = "{e}";
      description = "Trivial group — polynomial splits completely over ℚ.";
      break;
    }
    case "C_2": {
      // For a transitive C_2 on `degree` points: only meaningful for degree = 2.
      elements = closure([cycle(degree, [0, 1])], degree);
      prettyName = "ℤ/2";
      description = "Cyclic of order 2 — generated by one root-swap.";
      break;
    }
    case "C_3": {
      elements = closure([cycle(degree, [0, 1, 2])], degree);
      prettyName = "ℤ/3 (= A₃)";
      description = "Cyclic of order 3 — only even (3-cycle) permutations.";
      break;
    }
    case "S_3": {
      elements = closure([cycle(degree, [0, 1, 2]), cycle(degree, [0, 1])], degree);
      prettyName = "S₃";
      description = "Symmetric group of order 6 — every permutation of 3 roots is allowed.";
      break;
    }
    case "V_4": {
      // Klein four, as the subgroup of S_4 of double transpositions.
      elements = closure(
        [transpositions(degree, [[0, 1], [2, 3]]), transpositions(degree, [[0, 2], [1, 3]])],
        degree,
      );
      prettyName = "V₄ = ℤ/2 × ℤ/2";
      description = "Klein four-group — three independent root-pair swaps, all of order 2.";
      break;
    }
    case "C_4": {
      elements = closure([cycle(degree, [0, 1, 2, 3])], degree);
      prettyName = "ℤ/4";
      description = "Cyclic of order 4 — root rotation, splitting field is degree 4.";
      break;
    }
    case "D_4": {
      // Dihedral acting on 4 points: <(0 1 2 3), (0 2)>
      elements = closure(
        [cycle(degree, [0, 1, 2, 3]), cycle(degree, [0, 2])],
        degree,
      );
      prettyName = "D₄";
      description = "Dihedral of order 8 — root rotations and reflections; splitting field is degree 8.";
      break;
    }
    case "A_4": {
      // <(0 1 2), (1 2 3)>
      elements = closure([cycle(degree, [0, 1, 2]), cycle(degree, [1, 2, 3])], degree);
      prettyName = "A₄";
      description = "Alternating group on 4 points (order 12) — only even permutations.";
      break;
    }
    case "S_4": {
      elements = closure([cycle(degree, [0, 1, 2, 3]), cycle(degree, [0, 1])], degree);
      prettyName = "S₄";
      description = "Symmetric group on 4 points (order 24) — every permutation allowed; the generic case.";
      break;
    }
  }
  return {
    name,
    prettyName,
    order: elements.length,
    degree,
    elements,
    isAbelian: isAbelianGroup(elements),
    description,
  };
}

// ---- Subgroup lattices (hand-coded for the small Galois groups we use) ----

export type SubgroupNode = {
  id: string;
  name: GroupName | string;
  prettyName: string;
  order: number;
  elements: Perm[];
  fixedField?: string; // human-readable description of the fixed field
};

export type Lattice = {
  nodes: SubgroupNode[];      // sorted by order ascending
  edges: [string, string][];  // [smaller, larger] covering relations
};

// Build the (sub)lattice for a given top-level group, given root labels for fixed-field descriptions.
// rootLabels: string for each root, e.g. ["r₁", "r₂", "r₃", "r₄"] or specific like ["α", "−α", "iα", "−iα"].
export function buildLattice(
  top: GroupName,
  degree: number,
  rootLabels: string[],
  discDescription: string | null,
): Lattice {
  // Generic helper: compute subgroups via brute force for small groups.
  const G = makeNamedGroup(top, degree);
  const all = G.elements;
  const idK = permKey(permId(degree));
  // Find all subgroups by trying all subsets — only feasible for small groups.
  const N = all.length;
  if (N > 24) {
    return { nodes: [], edges: [] };
  }
  const allKey = all.map(permKey);
  const idxOf = new Map<string, number>(allKey.map((k, i) => [k, i] as const));
  function multiplyIdx(i: number, j: number): number {
    return idxOf.get(permKey(permCompose(all[i], all[j])))!;
  }
  function inverseIdx(i: number): number {
    return idxOf.get(permKey(permInverse(all[i])))!;
  }

  // Iterate subsets containing identity; check closure under multiplication & inverses.
  const idIdx = allKey.indexOf(idK);
  const subgroups: number[][] = []; // each is a sorted array of element indices
  const seen = new Set<string>();
  for (let mask = 0; mask < 1 << N; mask++) {
    if (!(mask & (1 << idIdx))) continue;
    // Check closure
    let ok = true;
    const idxs: number[] = [];
    for (let i = 0; i < N; i++) if (mask & (1 << i)) idxs.push(i);
    for (const i of idxs) {
      if (!(mask & (1 << inverseIdx(i)))) {
        ok = false;
        break;
      }
    }
    if (ok) {
      outer: for (const i of idxs) {
        for (const j of idxs) {
          if (!(mask & (1 << multiplyIdx(i, j)))) {
            ok = false;
            break outer;
          }
        }
      }
    }
    if (ok) {
      const key = idxs.join(",");
      if (!seen.has(key)) {
        seen.add(key);
        subgroups.push(idxs);
      }
    }
  }
  // Name the subgroups
  const nodes: SubgroupNode[] = subgroups.map((idxs, i) => {
    const elts = idxs.map((k) => all[k]);
    const name = identifySubgroup(elts);
    const ng = makeNamedGroup(name, degree);
    return {
      id: `H${i}`,
      name,
      prettyName: ng.prettyName,
      order: elts.length,
      elements: elts,
      fixedField: describeFixedField(elts, rootLabels, discDescription),
    };
  });
  // Sort by order
  nodes.sort((a, b) => a.order - b.order);
  // Covering relations: H < K with no intermediate.
  const idxByElt = new Map<string, number>(); // map sorted-elt key to index in nodes
  for (let i = 0; i < nodes.length; i++) {
    idxByElt.set(nodes[i].elements.map(permKey).sort().join("|"), i);
  }
  function isSubsetOf(small: SubgroupNode, large: SubgroupNode): boolean {
    if (small.order >= large.order) return small.order === large.order && permsEqualSet(small.elements, large.elements);
    const ls = new Set(large.elements.map(permKey));
    return small.elements.every((p) => ls.has(permKey(p)));
  }
  const edges: [string, string][] = [];
  for (let i = 0; i < nodes.length; i++) {
    for (let j = 0; j < nodes.length; j++) {
      if (i === j) continue;
      if (nodes[i].order >= nodes[j].order) continue;
      if (!isSubsetOf(nodes[i], nodes[j])) continue;
      // Check there's no k strictly between i and j
      let hasIntermediate = false;
      for (let k = 0; k < nodes.length; k++) {
        if (k === i || k === j) continue;
        if (nodes[k].order <= nodes[i].order || nodes[k].order >= nodes[j].order) continue;
        if (isSubsetOf(nodes[i], nodes[k]) && isSubsetOf(nodes[k], nodes[j])) {
          hasIntermediate = true;
          break;
        }
      }
      if (!hasIntermediate) edges.push([nodes[i].id, nodes[j].id]);
    }
  }
  return { nodes, edges };
}

function permsEqualSet(a: Perm[], b: Perm[]): boolean {
  if (a.length !== b.length) return false;
  const sa = new Set(a.map(permKey));
  return b.every((p) => sa.has(permKey(p)));
}

function identifySubgroup(elts: Perm[]): GroupName {
  const n = elts.length;
  if (n === 1) return "Trivial";
  if (n === 2) return "C_2";
  if (n === 3) return "C_3";
  if (n === 4) {
    // Either V_4 (no order-4 element) or C_4
    const orders = elts.map(permOrder);
    return orders.includes(4) ? "C_4" : "V_4";
  }
  if (n === 6) return "S_3";
  if (n === 8) return "D_4";
  if (n === 12) return "A_4";
  if (n === 24) return "S_4";
  // Fallback
  return "Trivial";
}

// A heuristic description of the fixed field of a subgroup H of Gal(f/Q),
// expressed in terms of the root labels.
//
// We describe the fixed field by listing simple H-invariant rational functions
// of the roots. Specifically:
//   - if H fixes a root individually, that root is in the fixed field
//   - if H permutes only within pairs, the sum/product of each orbit is in the field
//   - if H = whole group, fixed field is ℚ
//   - if H = trivial, fixed field is the whole splitting field
//
// For nuance about ℚ(√disc) etc, we add it when an index-2 subgroup looks like
// the even part (= A_n in S_n).
function describeFixedField(elts: Perm[], rootLabels: string[], discDescription: string | null): string {
  const n = rootLabels.length;
  if (elts.length === 1) return "splitting field K (the whole thing)";
  // Compute orbits of {0,...,n-1} under the subgroup.
  const orbit = Array(n).fill(-1);
  let nOrbits = 0;
  for (let start = 0; start < n; start++) {
    if (orbit[start] !== -1) continue;
    nOrbits++;
    const stack = [start];
    while (stack.length) {
      const x = stack.pop()!;
      if (orbit[x] !== -1) continue;
      orbit[x] = nOrbits - 1;
      for (const p of elts) {
        if (orbit[p[x]] === -1) stack.push(p[x]);
      }
    }
  }
  // Group root labels by orbit.
  const groups: number[][] = Array.from({ length: nOrbits }, () => []);
  for (let i = 0; i < n; i++) groups[orbit[i]].push(i);
  // Check if H = whole group (all roots in one orbit AND every permutation is in elts).
  // We use a simpler check: if any orbit has all n roots, it might still be a smaller subgroup.
  // Better: if elts list contains every permutation of degree n. We just rely on caller logic.
  const fixed = groups.filter((g) => g.length === 1).map((g) => rootLabels[g[0]]);
  const orbits = groups.filter((g) => g.length > 1);
  const parts: string[] = [];
  if (fixed.length > 0) parts.push(...fixed);
  for (const g of orbits) {
    // Use elementary symmetric functions: sum and product of the orbit.
    const labels = g.map((i) => rootLabels[i]);
    if (labels.length === 2) {
      parts.push(`${labels[0]}+${labels[1]}`);
      parts.push(`${labels[0]}·${labels[1]}`);
    } else {
      parts.push(`Σ{${labels.join(",")}}`);
      parts.push(`Π{${labels.join(",")}}`);
    }
  }
  // If the only orbit was the full set and H "looks like" A_n in S_n, add √disc.
  // Detect by: all permutations in elts are even. (For our small Galois groups this is meaningful.)
  if (parts.length === 0 || (orbits.length === 1 && orbits[0].length === n)) {
    // Check parity: all even?
    const allEven = elts.every((p) => parityOfPerm(p) === 0);
    if (allEven && discDescription) {
      return `ℚ(${discDescription})`;
    }
    return "ℚ";
  }
  return `ℚ(${parts.join(", ")})`;
}

export function parityOfPerm(p: Perm): 0 | 1 {
  // 0 = even, 1 = odd. Count inversions mod 2.
  let inv = 0;
  for (let i = 0; i < p.length; i++) {
    for (let j = i + 1; j < p.length; j++) {
      if (p[i] > p[j]) inv++;
    }
  }
  return (inv & 1) as 0 | 1;
}
