// Lattice math: exact rational linear algebra for basis checks, plus numeric
// lattice-point generation for plotting.
//
// A lattice L generated by vectors v₁..v_k is { a₁v₁ + … + a_k v_k : aᵢ ∈ ℤ }.
// With rational entries this is always a genuine (discrete) lattice; the
// interesting questions are its rank, whether the generators are a *basis*
// (i.e. linearly independent / non-redundant), and its covolume — the volume
// of a fundamental domain. All of those are computed exactly here.

import {
  rat,
  add,
  sub,
  mul,
  neg,
  div,
  isZero,
  toNumber,
  rationalSqrt,
  absBig,
  lcmBig,
  ZERO,
  ONE,
  type Rational,
} from "./rational";
import { sup } from "./notation";

export type RVec = Rational[];

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

// Parse one component: integer ("3", "-5"), fraction ("1/2", "-7/3"),
// or decimal ("0.5", "-1.25"). Everything becomes an exact Rational.
export function parseComponent(s: string): Rational {
  let t = s.trim();
  if (t === "") throw new Error("empty component");
  let sign = 1n;
  if (t[0] === "+") t = t.slice(1);
  else if (t[0] === "-") {
    sign = -1n;
    t = t.slice(1);
  }
  const frac = t.match(/^(\d+)\/(\d+)$/);
  if (frac) {
    if (frac[2] === "0") throw new Error("denominator is zero");
    return rat(sign * BigInt(frac[1]), BigInt(frac[2]));
  }
  const dec = t.match(/^(\d*)(?:\.(\d+))?$/);
  if (dec && (dec[1] !== "" || (dec[2] && dec[2] !== ""))) {
    const intPart = dec[1] === "" ? 0n : BigInt(dec[1]);
    const fracDigits = dec[2] ?? "";
    const denom = 10n ** BigInt(fracDigits.length);
    const num = intPart * denom + (fracDigits === "" ? 0n : BigInt(fracDigits));
    return rat(sign * num, denom);
  }
  throw new Error(`invalid number: "${s}"`);
}

// ---------------------------------------------------------------------------
// Rational vector / matrix helpers
// ---------------------------------------------------------------------------

export function dot(a: RVec, b: RVec): Rational {
  let s = ZERO;
  for (let i = 0; i < a.length; i++) s = add(s, mul(a[i], b[i]));
  return s;
}

export function isZeroVec(v: RVec): boolean {
  return v.every(isZero);
}

// Rank (dimension of the ℝ-span) via Gaussian elimination on the rows.
export function rankOf(rows: RVec[]): number {
  const m = rows.map((r) => r.slice());
  const nr = m.length;
  const nc = nr ? m[0].length : 0;
  let r = 0;
  for (let col = 0; col < nc && r < nr; col++) {
    let piv = -1;
    for (let i = r; i < nr; i++)
      if (!isZero(m[i][col])) {
        piv = i;
        break;
      }
    if (piv === -1) continue;
    [m[r], m[piv]] = [m[piv], m[r]];
    const pv = m[r][col];
    for (let i = r + 1; i < nr; i++) {
      if (!isZero(m[i][col])) {
        const f = div(m[i][col], pv);
        for (let c = col; c < nc; c++) m[i][c] = sub(m[i][c], mul(f, m[r][c]));
      }
    }
    r++;
  }
  return r;
}

// Determinant of a square rational matrix.
export function ratDet(mat: RVec[]): Rational {
  const n = mat.length;
  if (n === 0) return ONE;
  const m = mat.map((r) => r.slice());
  let det = ONE;
  for (let col = 0; col < n; col++) {
    let piv = -1;
    for (let i = col; i < n; i++)
      if (!isZero(m[i][col])) {
        piv = i;
        break;
      }
    if (piv === -1) return ZERO;
    if (piv !== col) {
      [m[col], m[piv]] = [m[piv], m[col]];
      det = neg(det);
    }
    det = mul(det, m[col][col]);
    const pv = m[col][col];
    for (let i = col + 1; i < n; i++) {
      const f = div(m[i][col], pv);
      for (let c = col; c < n; c++) m[i][c] = sub(m[i][c], mul(f, m[col][c]));
    }
  }
  return det;
}

// Gram determinant det(B · Bᵀ); equals (covolume)² for an independent set of rows.
function gramDet(rows: RVec[]): Rational {
  const r = rows.length;
  const g: RVec[] = [];
  for (let i = 0; i < r; i++) {
    g.push([]);
    for (let j = 0; j < r; j++) g[i].push(dot(rows[i], rows[j]));
  }
  return ratDet(g);
}

// ---------------------------------------------------------------------------
// Integer Hermite-style reduction → a canonical basis of the generated lattice
// ---------------------------------------------------------------------------

// Scale a set of rational vectors to integers by their common denominator.
function clearDenoms(rows: RVec[]): { ints: bigint[][]; denom: bigint } {
  let D = 1n;
  for (const row of rows) for (const x of row) D = lcmBig(D, x.d);
  const ints = rows.map((row) => row.map((x) => x.n * (D / x.d)));
  return { ints, denom: D };
}

// Basis of the integer row-span lattice (the nonzero rows of a row-style HNF).
// Combines rows by repeated gcd reduction per column.
export function integerRowBasis(rows0: bigint[][]): bigint[][] {
  const rows = rows0.map((r) => r.slice());
  const m = rows.length;
  const n = m ? rows[0].length : 0;
  let r = 0;
  for (let col = 0; col < n && r < m; col++) {
    for (;;) {
      let pivot = -1;
      let best = 0n;
      for (let i = r; i < m; i++) {
        const v = rows[i][col];
        if (v !== 0n) {
          const av = absBig(v);
          if (pivot === -1 || av < best) {
            pivot = i;
            best = av;
          }
        }
      }
      if (pivot === -1) break;
      if (pivot !== r) [rows[r], rows[pivot]] = [rows[pivot], rows[r]];
      const pv = rows[r][col];
      let changed = false;
      for (let i = r + 1; i < m; i++) {
        if (rows[i][col] !== 0n) {
          const q = rows[i][col] / pv;
          if (q !== 0n) for (let c = 0; c < n; c++) rows[i][c] -= q * rows[r][c];
          if (rows[i][col] !== 0n) changed = true;
        }
      }
      if (!changed) {
        r++;
        break;
      }
    }
  }
  const basis = rows.slice(0, r).map((row) => row.slice());
  // Normalize sign: first nonzero entry of each row positive.
  for (const row of basis) {
    for (const x of row) {
      if (x !== 0n) {
        if (x < 0n) for (let c = 0; c < n; c++) row[c] = -row[c];
        break;
      }
    }
  }
  return basis;
}

// ---------------------------------------------------------------------------
// Full analysis
// ---------------------------------------------------------------------------

export type AnalysisMessage = { kind: "good" | "warn" | "info"; text: string };

export type LatticeAnalysis = {
  dim: number; // ambient dimension
  enteredCount: number; // number of generators entered
  nonzeroCount: number; // generators that are not the zero vector
  rank: number; // dimension of the ℝ-span
  independent: boolean; // linearly independent ⇔ they are a basis of the generated lattice
  fullRank: boolean; // rank === dim
  hasZeroVector: boolean;
  redundant: boolean; // more generators than the rank
  canonicalBasis: RVec[]; // a basis of the generated lattice (rank vectors)
  covolumeSquared: Rational | null; // det of the lattice, squared (null if rank 0)
  covolumeExact: Rational | null; // covolume if it is rational, else null
  covolumeApprox: number; // numeric covolume
  messages: AnalysisMessage[];
};

export function analyzeLattice(vectors: RVec[], dim: number): LatticeAnalysis {
  const enteredCount = vectors.length;
  const nonzero = vectors.filter((v) => !isZeroVec(v));
  const hasZeroVector = nonzero.length < enteredCount;
  const rank = rankOf(vectors);
  const independent = enteredCount > 0 && rank === enteredCount && !hasZeroVector;
  const fullRank = rank === dim;
  const redundant = enteredCount > rank;

  let canonicalBasis: RVec[] = [];
  let covolumeSquared: Rational | null = null;
  let covolumeExact: Rational | null = null;
  let covolumeApprox = 0;

  if (rank > 0) {
    const { ints, denom } = clearDenoms(nonzero);
    const intBasis = integerRowBasis(ints);
    canonicalBasis = intBasis.map((row) => row.map((x) => rat(x, denom)));
    const gd = gramDet(canonicalBasis);
    covolumeSquared = gd;
    covolumeExact = rationalSqrt(gd);
    covolumeApprox = Math.sqrt(Math.max(0, toNumber(gd)));
  }

  const messages: AnalysisMessage[] = [];
  if (enteredCount === 0) {
    messages.push({ kind: "info", text: "Add at least one vector to generate a lattice." });
  } else if (rank === 0) {
    messages.push({
      kind: "warn",
      text: "Every generator is the zero vector — the lattice is just the origin {0}.",
    });
  } else {
    if (independent && fullRank) {
      messages.push({
        kind: "good",
        text: `Linearly independent and full rank: these vectors are a basis of a rank-${rank} lattice filling all of ℝ${sup(dim)}.`,
      });
    } else if (independent && !fullRank) {
      messages.push({
        kind: "good",
        text: `Linearly independent: a basis of a rank-${rank} lattice — a ${rank}-dimensional lattice sitting inside ℝ${sup(dim)}.`,
      });
    } else {
      messages.push({
        kind: "warn",
        text: `Linearly dependent: ${enteredCount} generators but rank ${rank}, so they are NOT a basis. At least one generator is redundant; a genuine basis is shown below.`,
      });
    }
    if (hasZeroVector) {
      messages.push({
        kind: "info",
        text: "A zero vector was entered; it contributes nothing to the lattice.",
      });
    }
    if (rank === 1 && nonzero.length >= 2) {
      messages.push({
        kind: "info",
        text: "All generators are collinear, so the lattice lies on a single line.",
      });
    }
  }

  return {
    dim,
    enteredCount,
    nonzeroCount: nonzero.length,
    rank,
    independent,
    fullRank,
    hasZeroVector,
    redundant,
    canonicalBasis,
    covolumeSquared,
    covolumeExact,
    covolumeApprox,
    messages,
  };
}

// ---------------------------------------------------------------------------
// Numeric helpers for plotting
// ---------------------------------------------------------------------------

export type Vec3 = [number, number, number];

export function toNumVec(v: RVec): number[] {
  return v.map(toNumber);
}

// Embed a vector of dimension ≤ 3 into 3-space by zero-padding.
export function embed3(v: number[]): Vec3 {
  return [v[0] ?? 0, v[1] ?? 0, v[2] ?? 0];
}

function within(p: Vec3, radius: number): boolean {
  return Math.abs(p[0]) <= radius && Math.abs(p[1]) <= radius && Math.abs(p[2]) <= radius;
}

// Enumerate integer combinations of the (already embedded) basis vectors,
// keeping points inside a cube of half-width `radius`, deduped, capped.
export function latticePoints(
  basis3: Vec3[],
  rank: number,
  n: number,
  radius: number,
  maxPoints = 6000,
): Vec3[] {
  const pts: Vec3[] = [];
  const seen = new Set<string>();
  const push = (p: Vec3): boolean => {
    const key = `${Math.round(p[0] * 1e4)},${Math.round(p[1] * 1e4)},${Math.round(p[2] * 1e4)}`;
    if (seen.has(key)) return true;
    seen.add(key);
    pts.push(p);
    return pts.length < maxPoints;
  };
  push([0, 0, 0]);
  const r = radius * 1.0001;
  if (rank >= 1) {
    const b1 = basis3[0];
    if (rank === 1) {
      for (let a = -n; a <= n; a++) {
        const p: Vec3 = [a * b1[0], a * b1[1], a * b1[2]];
        if (within(p, r) && !push(p)) return pts;
      }
    } else if (rank === 2) {
      const b2 = basis3[1];
      for (let a = -n; a <= n; a++)
        for (let b = -n; b <= n; b++) {
          const p: Vec3 = [
            a * b1[0] + b * b2[0],
            a * b1[1] + b * b2[1],
            a * b1[2] + b * b2[2],
          ];
          if (within(p, r) && !push(p)) return pts;
        }
    } else {
      const b2 = basis3[1];
      const b3 = basis3[2];
      for (let a = -n; a <= n; a++)
        for (let b = -n; b <= n; b++)
          for (let c = -n; c <= n; c++) {
            const p: Vec3 = [
              a * b1[0] + b * b2[0] + c * b3[0],
              a * b1[1] + b * b2[1] + c * b3[1],
              a * b1[2] + b * b2[2] + c * b3[2],
            ];
            if (within(p, r) && !push(p)) return pts;
          }
    }
  }
  return pts;
}
